# This is a basic workflow to help you get started with Actions

name: Deploy Apps

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only when there is new Tags **** on branch "main"
  push:
    tags:
      - 'v*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: Run a one-line script
      run: echo Hello, comenzando Build and Deploy on Docker-compose!

    - name: Valor variables de ambiente PREDEFINIDAS, eliminar al final
      run: |
        echo "Repositorio: $GITHUB_REPOSITORY"
        echo "Rama: $GITHUB_REF"
        echo "Tag: $GITHUB_REF_NAME"
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push app1
      run: |
        docker build -t aastorga2019/app1:${{ github.ref_name }} ./app1
        docker push aastorga2019/app1:${{ github.ref_name }}

    - name: Build and push app2
      run: |
        docker build -t aastorga2019/app2:${{ github.ref_name }} ./app2
        docker push aastorga2019/app2:${{ github.ref_name }}

#ojo, si cambia ip pub, no sirve de nada
#    - name: Agregar clave del Server a un archivo personalizado known_hosts 
#      run: |
#        mkdir -p ~/.ssh
#        ssh-keyscan -H 186.107.180.35 >> ~/.ssh/custom_known_hosts

#ip local 192.168.1.143, publica 186.107.180.35 (es variable) // inseguro flag -o Stric... sólo para bypasear pass 
    - name: Deploy for shh to server last version APPs
      run: ssh -o StrictHostKeyChecking=no a.astorga@186.107.180.35 "cd /Users/a.astorga/Documents/Proyectos/Latam/Revisar/dockerCompose-github-casouso-2apps && docker-compose pull && docker-compose up -d"
#      run: ssh -o UserKnownHostsFile=~/.ssh/custom_known_hosts a.astorga@186.107.180.35 "cd /Users/a.astorga/Documents/Proyectos/Latam/Revisar/dockerCompose-github-casouso-2apps && docker-compose pull && docker-compose up -d"
