# This is a basic workflow to help you get started with Actions

name: Deploy Apps

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only when there is new Tags **** on branch "main"
  push:
    tags:
      - 'v*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run a one-line script
      run: echo Hello, comenzando Build and Deploy on Docker-compose!

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push app1
      run: |
        docker build -t aastorga2019/app1:${{ github.ref_name }} ./app1
        docker push aastorga2019/app1:${{ github.ref_name }}

    - name: Build and push app2
      run: |
        docker build -t aastorga2019/app2:${{ github.ref_name }} ./app2
        docker push aastorga2019/app2:${{ github.ref_name }}

    - name: Deploy to server
      run: ssh a.astorga@localhost "cd /Users/a.astorga/Documents/Proyectos/Latam/Revisar/dockerCompose-github-casouso-2apps && docker-compose pull && docker-compose up -d"
